### ISSUE TITLE
[Question] Kotlin 1.4.30 

### ISSUE THREAD

**Issue by dinorahto** [square/anvil#195]
Hello! 
I have a question, I'm getting this error using Anvil in Kotlin 1.4.30 but actually works fine with other versions [1.4.21], could be my setup, the app only has a module and is pretty much empty. 
I don't know if this has to do with Anvil, sorry if not 

`java.lang.NoSuchMethodError: org.jetbrains.kotlin.analyzer.AnalysisResult$RetryWithAdditionalRoots.<init>(Lorg/jetbrains/kotlin/resolve/BindingContext;Lorg/jetbrains/kotlin/descriptors/ModuleDescriptor;Ljava/util/List;Ljava/util/List;Z)V
	at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted(CodeGenerationExtension.kt:81`

**Comment by vRallev** [comment]
This is a duplicate of #190. Make sure you use the latest Anvil version: https://github.com/square/anvil/releases/tag/v2.1.0

**Comment by dinorahto** [comment]
Thanks!
