### ISSUE TITLE
NoSuchMethodError when applying plugin with Gradle < 7.1

### ISSUE THREAD

**Issue by RBusarow** [square/anvil#387]
This was introduced in #353 and was released in 2.3.4.

If the plugin's applied to a project still using anything prior to 7.1, it'll cause this exception:

```
Caused by: java.lang.NoSuchMethodError: 'org.gradle.api.tasks.SourceSetContainer org.gradle.api.plugins.JavaPluginExtension.getSourceSets()'
        at com.squareup.anvil.plugin.CheckMixedSourceSet.getJvmSourceDirs(CheckMixedSourceSet.kt:57)
        at com.squareup.anvil.plugin.CheckMixedSourceSet.preparePreciseJavaTrackingCheck(CheckMixedSourceSet.kt:24)
        at com.squareup.anvil.plugin.AnvilPlugin$disablePreciseJavaTracking$configureAction$1.invoke(AnvilPlugin.kt:166)
        at com.squareup.anvil.plugin.AnvilPlugin$disablePreciseJavaTracking$configureAction$1.invoke(AnvilPlugin.kt:165)
        at com.squareup.anvil.plugin.AnvilPlugin.disablePreciseJavaTracking$lambda-7(AnvilPlugin.kt:183)
...
```

I only found this because of some matrix tests which were running against 6.9.1 and 7.0.2, but I'm surprised no one has created an issue already.  Maybe anyone cool enough to use Anvil is also on the latest and greatest Gradle version?

**Comment by vRallev** [comment]
I'll close the ticket therefore.
